### ISSUE TITLE
Incorrect pop

### ISSUE THREAD

**Issue by Incubatio** [mourner/tinyqueue#11]
Script and reproduce case below:
```js
TinyQueue = require('./index.js')
q = new TinyQueue()
lpush = function(a) { console.log('push', a); q.push(a) };
lpop = function() { console.log('pop', q.pop());  };

lpush(0);
lpop(); // 0 (correct)

lpush(2);
lpush(5);
lpop() // pop 2 (correct)

lpush(4);
lpop() // pop 2 (should be 4)
lpop() // pop 2 (should be 5)
lpop() // pop undefined (correct)
```

As I said in another issue I just dropped tinyqueue for another lib, so I won't fix it.
But maybe someone will have fun debugging it.

**Comment by mourner** [comment]
Maybe you've tested against a locally modified version? Here's me adding a test above and it passes the CI: https://github.com/mourner/tinyqueue/compare/small-fixes?expand=0

**Comment by Incubatio** [comment]
Indeed, good job :) !
