### ISSUE TITLE
Package 'module' field is in ES6 syntax -- incompatible with IE

### ISSUE THREAD

**Issue by josephliccini** [mourner/tinyqueue#12]
Hi,

I am trying to consume this package with webpack, which will use the `module` field in `package.json`.

That `module` field points to a ES6 version of the package.  I believe `module` should be used for ES6 `import` / `export` syntax, but still needs to be runtime compatible with ES5.

This leads to webpack pulling in an ES6 `class` which causes a syntax error in IE.

**Comment by mourner** [comment]
This is intentional. See an equivalent discussion [here](https://github.com/mourner/flatbush/issues/23#issuecomment-465498862).
