### ISSUE TITLE
init with empty array add undefined to data.

### ISSUE THREAD

**Issue by seokgyo** [mourner/tinyqueue#3]
Hi,

Initializing tinyqueue w/ empty array add undefined to data.

q = new require('tinyqueue')([])

{ data: [ undefined ],
  length: 0,
  compare: [Function: defaultCompare] }

**Comment by mourner** [comment]
Sorry for those 1.2.0 regressions, released the fix with 1.2.2. The module certainly needed better test coverage.

**Comment by seokgyo** [comment]
Thanks for the quick fix. 👍
