### ISSUE TITLE
[Fork Information]: Commented Version Of This Module

### ISSUE THREAD

**Issue by gdad-s-river** [mourner/tinyqueue#6]
I stumbled upon this module through [these chain of events](https://twitter.com/gdad_s_river/status/934363273029230592).

Being a noob both in programming at large and computer science in general, stumbling upon this module as the first implementation of heap data structure took me time to understand it. So I commented the code in the best way I could, so that noobs of the future could understand it a little easily, if they happen to stumble upon it the same (or different) way I did.

So I thought I would just open an issue to chain the information of the [commented fork](https://github.com/gdad-s-river/tinyqueue) I made of this module.

That's it! 😅

**Comment by mourner** [comment]
Glad you stumbled upon this module, and thanks for the comments :)
